### ISSUE TITLE
Incompatibility with Canary Mod

### ISSUE THREAD

**Issue by CGMejia2001** [coco875/C2ME-fabric#5]
crashes no startup and notable line from the log is: 
[pool-5-thread-1/WARN] [mixin/]: @Redirect conflict. Skipping canary.mixins.json:alloc.nbt.CompoundTagMixin from mod canary->@Redirect::removeOldMapAlloc()Ljava/util/HashMap; with priority 1000, already redirected by c2me-opts-allocs.mixins.json:MixinNbtCompound from mod c2me_opts_allocs->@Redirect::redirectNewHashMap()Ljava/util/HashMap; with priority 1100

log: https://pastebin.com/hBQdfA2H

**Comment by coco875** [comment]
you have a lot of mod try reproduce the problem in a clean instance with less mods

**Comment by coco875** [comment]
ok use radium instead (I try with radium and it work fine)
